### ISSUE TITLE
Various error handling issues

### ISSUE THREAD

**Issue by wjagodfrey** [theganyo/swagger-node-runner#48]
Hi there, I'm having a hard time with error handling. When a validation error is raised it comes back as an ugly JSON response with my request buffer attached. How do developers opt out, or modify this error object?

I am using a project generated with `swagger project create`, with `express`.

The other thing, is that the swagger error responses are coming back clipped. Example:

```
{"message":"Response validation failed: failed schema validation","code":"SCHE
```

This may be related to #30

Am I please able to have some help in resolving these issues?

Many thanks,
Wilfred

**Comment by wjagodfrey** [comment]
Truncated response seems to have been caused by:
https://github.com/swagger-api/swagger-node/issues/410#issuecomment-233791308

**Comment by tanzim** [comment]
Is that request or response validation that you're having issues with?  

If it's request validation, you can write your own error handling `fitting` (which is very much like an express middleware) to handle validation errors and customise what's sent to the client. I a

### Step 1
you'll need to update your swagger configuration in `{project_root}/config/default.yaml` to override the default json_error_handler with your own. For example, change:
```yaml
swagger_controllers:
      - onError: json_error_handler
```
To
```yaml
swagger_controllers:
      - onError: errorFitting
```

### Step 2
Create fitting `errorFitting` by creating `{project_root}/api/fittings/errorFitting.js`. To start with, you can just copy the [existing json_error_handler](https://github.com/theganyo/swagger-node-runner/blob/master/fittings/json_error_handler.js) into this and then customise it. You can detect if there was a validation error by looking at the error message [like the tests does](https://github.com/theganyo/swagger-node-runner/blob/master/test/lib/common.js#L171).

By the way, I saw that you were using raw res.send etc. from your code. I think you could do a lot better by abstracting that away and use something like [http-errors](https://github.com/jshttp/http-errors) to simplify controller code and take advantage of middleware chaining via `next` in express, which is also honoured by `swagger-node-runner`. For example, here's how a controller function in our codebase looks like:

```javascript
const createError = require('http-errors');
const createSuccess = require('http-success');
...
function register(req, res, next) {
  const user = req.swagger.params.body.value;
  authService.register(user, context, (error, result) => {
    if (error) {
      if (error instanceof ResourceError) return next(createError(error.status, error.message));
      if (error instanceof DatabaseError) return next(createError(error.status, error.message));
      return next(createError(401));
    }
    return next(null, createSuccess(200, result.data));
  });
}
```

**Comment by cjrd** [comment]
Adding this documentation to swagger-node along with some supporting docs would be very helpful: e.g. I'm not sure what "fittings" are, or why the error handler has to go in a subdirectory named "fittings". =)

**Comment by wjagodfrey** [comment]
@tanzim Thanks for the reply, I will give fittings a try immediately.

The other issue mentioned is a response validation defect - my comment here describes it in better detail:
https://github.com/swagger-api/swagger-node/issues/410#issuecomment-233791308

I believe it could have been resolved by the unmerged pull request linked above.

This is an issue with response validation not overwriting the `Content-Length` header after overwriting the response body, resulting in a truncated error message. I would say that this is clearly a bug, right?

It will not appear for request validation as controllers are not hit before an error is thrown, and response validation is bypassed (Thereby avoiding the issue).

**Comment by theganyo** [comment]
@wjagodfrey - Overwriting the response during response validation was deemed problematic in a number of ways and removed as of 0.6.4. See: https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.4. What version are you running?

**Comment by wjagodfrey** [comment]
@theganyo This took a bit of digging to figure out. Thanks for giving me a thread to pull at.

So to get started, I used the latest `swagger-node`'s project generator (`0.7.5`, as published to NPM) to generate a project.

Looking at the express skeleton, it uses:

https://github.com/swagger-api/swagger-node/blob/v0.7.5/project-skeletons/express/package.json#L12

We see:

```
"swagger-express-mw": "^0.1.0"
```

This is the case in every version tag for `swagger-node` that I looked at, including master.

This dep leads to this `package.json`:

https://github.com/apigee-127/swagger-express/blob/0.1.0/package.json#L19

With the line:

```
"swagger-node-runner": "^0.5.0"
```

Which means that any project generated with `swagger-node`'s express generator won't have this fix.

If we can update the `swagger-node` project skeleton to point at

```
"swagger-express-mw": "^0.6.0"
```

Instead of `0.1.0`, and update the skeleton accordingly, this would resolve the issue.

Considering you are a contributor to the `swagger-node` `package.json` in question @theganyo, are you able to take a look at this?

I have opened an issue here:
https://github.com/swagger-api/swagger-node/issues/416

**Comment by theganyo** [comment]
I wish I could. However, I have documented the exact steps necessary to do the upgrade here: https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.0.

**Comment by wjagodfrey** [comment]
That's a shame. Are there plans to upgrade the generator in the future?

Thank you for linking this release documentation. It was very helpful. I'm guessing `0.6.4`'s response validation resolves the breaking change note regarding response validation lacking in `0.6.0`?

**Comment by wjagodfrey** [comment]
Have just gone through release notes up to release `0.6.16` - useful documents. It would be nice to have this properly documented in a readme or wiki.

Thanks though, this looks like what I need. I'll get back to you if I hit a wall.

**Comment by wjagodfrey** [comment]
@theganyo I've set up a fitting as described and it doesn't appear to be functioning. Additionally, any logging inside of the fitting is not appearing in stdout.

Hard to debug, as it won't throw an error if it can't find:

```
swagger_controllers:
      - onError: bogus_handler
```

for example.

Any thoughts why this won't work for me?

Running:
```
project
└─┬ swagger-express-mw@0.6.0
  └── swagger-node-runner@0.6.16
```

**Comment by wjagodfrey** [comment]
It works if I use the 'json_error_handler` fitting name for the fitting file, and ignores whatever is configured in `default.yaml`.

A little more detail:

I have multiple swagger applications running as nested express applications. Each swagger application sets its own basePath:

```
[...]
var swaggerConfig = {
  appRoot: __dirname // <---
};

SwaggerExpress.create(swaggerConfig, function(err, swaggerExpress) {
  if (err) { throw err; }
[...]
```

This works well for all other cases. It seems to me that there is probably a bug with the onError fitting name configuration.

**Comment by theganyo** [comment]
Hey Wilfred,

1. You'll be pleased to know that I've (finally!) updated the [readme](https://github.com/theganyo/swagger-node-runner) to include references to the release notes.

2. I just finished releasing 0.7.0 that upgrades to Sway 1.0, so you may be interested in that (although I doubt very much that will fix your issue).

3. Hmm. I'm not sure about your issue. You should definitely receive an error if you have an invalid error handler name. Also, the json_error_handler fitting name isn't hard-coded in any way. How are you defining your custom error handler fitting in your default.yaml file?

**Comment by wjagodfrey** [comment]
1. Very nice, that seems like a good way of doing it.

2. That is interesting, I'll be sure to pull it when you're done.

3. As you outlined above. Here's my full defaults file. Note the onError fitting name, which doesn't match any fitting that I have defined:

```
# swagger configuration file

# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: stuff_error_handler
      - cors
      - swagger_params_parser
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

# any other values in this file are just loaded into the config for application access...
```
