### ISSUE TITLE
Existing security handler broken after upgrade to Sway 1.0 based release

### ISSUE THREAD

**Issue by tanzim** [theganyo/swagger-node-runner#53]
Hi,
Firstly congrats on the Sway 1.0 based release. Much appreciated. It seems that after the release, my existing security handlers are no longer working.

Pre-upgrade `npm ls` shows I had been using:
swagger-express-mw@0.6.0
swagger-node-runner@0.6.16
sway@0.6.0

I should mention that I was using API level security instead of specifying security per route, i.e. in my `swagger.yaml` file I had:

```yaml
# API security. Applies to all routes
security:
  - BasicAuth: []
# Routes
paths:
  /stars/{starId}/accounts:
    x-swagger-router-controller: star-controller
    get:
      description: Returns accounts for a star identified by it's id
...
# API security definition
securityDefinitions:
  BasicAuth:
    type: basic
```

Post upgrade, I'm using:
swagger-express-mw@0.7.0
swagger-node-runner@0.7.0
sway@1.0.0

Looking at the security fitting[1] it seems that `operation` comes back as `undefined` and this suggests that support for API level security has somehow been broken.

I've currently worked around by specifying operation level security for each route and that's fine, but I wanted to highlight this nevertheless as API level security is part of the spec and should be supported.  

[1] https://github.com/theganyo/swagger-node-runner/blob/master/fittings/swagger_security.js#L32
