### ISSUE TITLE
compeating efforts to JSON.stringify ctx.output

### ISSUE THREAD

**Issue by osher** [theganyo/swagger-node-runner#73]
Hi.
I noted compeating efforts between:
https://github.com/theganyo/swagger-node-runner/blob/master/fittings/json_error_handler.js#L42
https://github.com/theganyo/swagger-node-runner/blob/master/fittings/json_error_handler.js#L60
and
https://github.com/theganyo/swagger-node-runner/blob/master/lib/connect_middleware.js#L127

If the concern of serializing a model object to string is a concern of the `connect_middleware`, then the `json_error_handler` should not stringify, but leave a model object (if it's necessary at all...)

I came to this thought when I approached a requirement to format error responses with a custom header that is accustomed in the corp I do the job for.

My initial thought was :
```
swagger-route-error:
 - name: json_error_handler
 - fitting/the-corp-envelope

swagger-router:
 - onError: swagger-route-error
 - ...
```

Then I noted that the error handler leaves a string. If I want to manipulate it - I'll have to parse it, where it was an object just one step before...

.

I began to believe that the safe serialization logic belongs to `connect_middleware`, and should be agnostic to wether it's an error or not
