### ISSUE TITLE
Not possible to configure CORS origin using a regexp

### ISSUE THREAD

**Issue by dcolens** [theganyo/swagger-node-runner#77]
https://github.com/expressjs/cors#configuration-options shows that you can set origin to a regexp to only allow CORS request from a given domain:

> RegExp - set origin to a regular expression pattern which will be used to test the request origin. If it's a match, the request origin will be reflected. For example the pattern /example\.com$/ will reflect any request that is coming from an origin ending with "example.com".

Is there a way to pass such a regexp in the config ? If not, how may I create my own cors middleware and use it in the swagger-node-runner setup ?

**Comment by tanzim** [comment]
You can configure CORS. Change your config/<environment>.yaml file to include the configuration for cors like this:

```yaml
cors:
      name: cors
      origin: [ !!js/regexp /localhost\:.*/, !!js/regexp /127\.0\.0\.1\:.*/ ]
```
